spring:
  application:
    name: dine-in-order-api
  datasource:
    url: jdbc:mysql://localhost:3306/dine_in_order_db?createDatabaseIfNotExist=true
    username: root
    password: tiger
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

